CREATE DATABASE IF NOT EXISTS curve_1 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS curve_2 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'curve_1'@'%' IDENTIFIED BY 'cHchca3cHAZ2CELX';
CREATE USER IF NOT EXISTS 'curve_2'@'%' IDENTIFIED BY '2AMzBsa52WGwPkhG';

GRANT ALL PRIVILEGES ON curve_1.* TO 'curve_1'@'%';
GRANT ALL PRIVILEGES ON curve_2.* TO 'curve_2'@'%';

FLUSH PRIVILEGES;